### ISSUE TITLE
🐞 [Bug]: Locally connected node reports Hop Count of 1

### ISSUE THREAD

**Issue by RPN707** [meshtastic/firmware#4318]
### Firmware Version

2.3.13

### What did you do?

Updated FW to 2.3.13. Allowed iOS to update app to 2.3.11 (1025)

### Expected Behavior

Would expect node connected to via Bluetooth to not report a hop count

### Current Behavior

iOS 17.5.1 - FW 2.3.13 - App 2.3.11 (1025)
Tried 3 nodes, T-Echo, RAK 4631, Heltec V3. All same behavior.
Uninstalled and reinstalled app.
Since updating app to 2.3.11, node shows "rabbit" hop count of 1 when connected via Bluetooth in the node list.

![Image](https://github.com/meshtastic/Meshtastic-Apple/assets/173195027/dc2591fe-1b6e-49bf-8a89-72a5d88dcb43)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fifieldt** [comment]
@RPN707 , do you still see this in the latest firmware?

**Comment by thebentern** [comment]
This was fixed in #4618

**Comment by RPN707** [comment]
I'm only on 2.4.2 but, yes, I do still see a hop count on a BT connected node as of this morning.
