### ISSUE TITLE
[Bug]: CLIENT_BASE DMs should not auto-favorite

### ISSUE THREAD

**Issue by thebentern** [meshtastic/firmware#8556]
### Category

Other

### Hardware

Not Applicable

### Is this bug report about any UI component firmware like InkHUD or Meshtatic UI (MUI)?

- [ ] Meshtastic UI aka MUI colorTFT
- [ ] InkHUD ePaper
- [ ] OLED slide UI on any display

### Firmware Version

2.7.X

### Description

Currently I believe we have implemented automatic flavoriting upon DMing another node in all app platforms. This is generally considered desirable behavior as it ensures that the public keys are retained in the nodedb of the device. However, we have one context where this is extremely problematic, which is in the CLIENT_BASE role. In this role, we would be unintentionally creating routing issues for nodes which are not explicitly favorited by the user for relay out of their home base nodes.

### Relevant log output

```Shell

```

**Comment by Xaositek** [comment]
Slightly complex as Multi Message Storage (https://github.com/meshtastic/firmware/pull/8182) completely re-worked how Canned Message does this.

Addressed with this commit:
https://github.com/meshtastic/firmware/pull/8182/commits/e2d44829fee99bb9f14da89b28456307539d3ef6

**Comment by compumike** [comment]
I think https://github.com/meshtastic/firmware/pull/8495 fixes this issue. It's actually happening in the firmware, not in the clients. The clients send an `add_contact` `AdminMessage` before every DM. And currently that also favorites the node. My small firmware PR https://github.com/meshtastic/firmware/pull/8495 removes that when `CLIENT_BASE`.

**Comment by aerodan** [comment]
Still exists in 2.7.14 latest available alpha and iOS2.7.5 (1683) latest. Confirmed that the behavior of DM'ing a node also favorites it, and exhibits router behavior for same node. It is also bidirectional: if remote client favorites my node it becomes same in my list, or if I DM a node. Maybe this feature could be reassigned to another function other than Favorite, perhaps just a "Roof Router" tag?

**Comment by dzid26** [comment]
I think it was a mistake to reuse Favorite for  CLIENT_BASE role. 
I think it would've been better if only nodes that have certain (e.g. "Home") private channel opened with the CLIENT_BASE node to be prioritized. It would also solve https://github.com/meshtastic/firmware/discussions/8367
